export const portfolioData = [
  // Photography (4 programs)
  {
    id: 'photo1',
    title: 'Urban Echoes',
    category: 'photography',
    type: 'Digital Photography',
    year: '2025',
    description: 'A series of architectural photography exploring the relationship between light and their surrounding environment through the lens of a camera.',
    detailDescription: 'An exploration of urban architecture and its emotional resonance, capturing the interplay between light and shadow in Old Quebec. This photograph was taken during the golden hour when the ancient stone walls came alive with warm, dancing shadows that seemed to whisper stories of centuries past.',
    technique: 'Digital Photography with Natural Light',
    equipment: 'Canon EOS 6D, 15-35mm f/2.8 Lens',
    digitalTools: 'Adobe Lightroom Classic',
    physicalTools: 'Canon EOS 6D, 15-35mm f/2.8 Lens',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Personal Project',
    designIntentions: 'I aimed to capture the duality of urban environments by using architectural reflections to blend built and natural spaces, creating a dialogue between human-made structures and their organic surroundings.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1ZFAwq9soEPUX87PrbjGc04u7wX1meSYW?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1GUqstoi4D6Mg-pSEvBlkqBKbtNOIoSW2?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1ceV_FZcj7p2hklBrnVktfNex5RBuQNO0?w=800&h=800'
  },
  {
    id: 'photo2',
    title: 'Morning Solitude',
    category: 'photography',
    type: 'Documentary Photography',
    year: '2025',
    description: 'Documentary portrait series focusing on the relationship between natural landscapes and human architecture.',
    detailDescription: 'Captured during golden hour, this piece examines the relationship between natural landscapes and human architecture through intimate framing. The soft morning light creates a dialogue between the organic curves of the landscape and the geometric precision of architectural elements.',
    technique: 'Natural Light Photography',
    equipment: 'Canon EOS RP, Kit Lens',
    digitalTools: 'Adobe Lightroom Classic',
    physicalTools: 'Canon EOS RP, Kit Lens',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Class Assignment - Mentor Challenge',
    designIntentions: 'My goal was to showcase the relationship of nature and architecture by using photogrpahy as a storyteller, using dramatic lighting to emphasize character while maintaining an intimate, insightful perspective.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1Cm-uf2NKLUCgj_IKaglS4KLj_RRxR7FH?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1e1qDiM1cYaxoW4TE_f3_2py1lhJ-pumd?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1STf7QNiTasnAuTXkGuO0VnyoxLhXDAoC?w=800&h=800'
  },
  {
    id: 'photo3',
    title: 'The Getty',
    category: 'photography',
    type: 'Travel Photography',
    year: '2025',
    description: 'A glimpse into the Getty, where timeless architecture meets the pull of nostalgia and shared cultural memory.',
    detailDescription: 'The Getty holds more than masterpieces — it cradles the quiet ache of nostalgia coupled with the charm of an older happier time. This image captures not just the architectural beauty of the museum, but the emotional resonance of spaces that house collective cultural memory.',
    technique: 'Travel Photogrpahy',
    equipment: 'Nikon D3300, 50-200mm f/2.8',
    digitalTools: 'Adobe Lightroom Classic',
    physicalTools: 'Nikon D3300, 50-200mm f/2.8',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Personal Project',
    designIntentions: 'To evoke a sense of quiet nostalgia through architectural framing and warm natural light capturing the Getty as a vessel of collective memory and emotional stillness.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1x08s54SJRkveQ_fC3EVsZb5-Tt6m_fuX?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1TvgyV3xi51OzwDNbbfrQbcCC0Q-gY45Z?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1UQj-b55ZeVroux0pIDaFfpqdpn-vR6oZ?w=800&h=800'
  },
  {
    id: 'photo4',
    title: 'Hidden Art',
    category: 'photography',
    type: 'Street Photography',
    year: '2025',
    description: 'Candid street photography capturing the spontaneous poetry of urban life and human interaction in public spaces.',
    detailDescription: 'Part of a series exploring human expression and emotion through ancient and contemporary composition. This piece investigates the layers of meaning hidden within artistic representation, questioning what remains visible and what is obscured in the translation between different artistic mediums.',
    technique: 'Street Photography',
    equipment: 'Canon EOS RP, Kit Lens',
    digitalTools: 'Adobe Lightroom Classic',
    physicalTools: 'Canon EOS RP, Kit Lens',
    originalSize: '2" x 3" (Digital Print)',
    medium: 'Digital Photography',
    assignmentStatus: 'Personal Project',
    designIntentions: 'I aimed to capture the authentic, unposed moments that reveal the humanity and character of urban life, using natural light and compositions\ to tell stories about art and history in the city.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1zUmfWRwPYTLdUrdUtKrnyR-7Fx6K1L9R?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1S6eX5I3J6TLBDi84-Y3Smyh4jl9LxXn8?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1b6bfVw8q0KOPwckRDAiFZAN1z7YkZKV1?w=800&h=800'
  },

  // 3D Design (2 programs)
  {
    id: '3d1',
    title: 'Neptune',
    category: '3d',
    type: '3D Architectural Visualization',
    year: '2024',
    description: 'A FIRST Robotics bot built my team 9477 Lambda.',
    detailDescription: 'A bot built under a tight budget as a rookie team placing top ten in the state winning engineering inspiration rewards in 2 competitions for its innovative use of pneumatic pistons.',
    technique: '3D Modeling, Machening, Electrical Wireing, Marketing, Documentation',
    equipment: 'Basic Mechnical Engineering tools',
    digitalTools: 'On-Shape, Adobe Lightroom, Adobe Illustrator, Canva, Github',
    physicalTools: 'Desktops, Basic Engineering Tools',
    originalSize: '28" x 28"',
    medium: '3D Digital Rendering, Phyical Build',
    assignmentStatus: 'Class Assignment - Club',
    designIntentions: 'My job was to prototype and built neptune coral intake, document club affairs, market the club, and create social media with graphics for the club, When desiging neptune we aimed to set ourselves apart by using pneumatic pistons something thats very rare to see in a FIRST Robotics Bot.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1Cra0jeg4ONj5UaZEdVZyPuSQDzgRN7wi?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1a2Fff0Ok_rJt4TD6z2gCAjyBBwQJSyKk?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1YezSSLf_8wwo7uACSNLFs5YI495NfaZG?w=800&h=800'
  },
  {
    id: '3d2',
    title: 'Ergonomic Desk Accessory Line - Work in Progress',
    category: '3d',
    type: 'Product Design Visualization',
    year: '2024',
    description: 'Industrial design project featuring a cohesive line of ergonomic desk accessories with focus on user comfort and minimal aesthetics.',
    detailDescription: 'This product design suite addresses common workplace ergonomic issues through thoughtful form and function. Each piece was modeled with attention to manufacturing constraints and user experience.',
    technique: 'Parametric Modeling and Product Visualization',
    equipment: 'SolidWorks, KeyShot Pro, Blender for Organic Modeling',
    digitalTools: 'SolidWorks, KeyShot Pro, Blender, Fusion 360, Adobe Creative Suite',
    physicalTools: 'Wacom Cintiq 22 Display Tablet, Calipers, Reference Materials, 3D Printed Prototypes',
    originalSize: '24" x 18" (Product Sheet Layout)',
    medium: '3D CAD Modeling, KeyShot Rendering',
    assignmentStatus: 'Personal Project',
    designIntentions: 'I focused on creating products that seamlessly integrate ergonomic function with clean, modern aesthetics, ensuring each piece could work independently while maintaining visual cohesion as a complete system.',
    imageUrl1: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=800',
    imageUrl2: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=800',
    featuredImageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&h=800'
  },

  // 2D Design (4 programs)
  {
    id: '2d1',
    title: 'Merdian Collection',
    category: '2d',
    type: 'Social Media Design Account',
    year: '2025',
    description: 'Complete social media account made up of a team of 4 people creating designs and showing off their passions.',
    detailDescription: 'This social media account was made by a group of 4 people who specilized in Graphic Design, Photography,and Videography.',
    technique: 'Graphic Design, Photography,and Videography',
    equipment: 'Adobe Illustrator, Photoshop, Adobe Premiere Pro',
    digitalTools: 'Adobe Illustrator, Adobe Photoshop, Adobe Premiere Pro',
    physicalTools: 'Desktops and Laptops',
    originalSize: 'Instagram Social Media Page',
    medium: 'Instagram',
    assignmentStatus: 'Passion Project',
    designIntentions: 'Meridian Collection started off as a small little joke that a group of friends started but then shifted into a full fledged account noticed by the Georgia DECA Instagram Page and The Getty Instagram Page. We grew this page from a small account ment as a joke to a account with a couple hundred followers.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/159m7eiY29850XVVaRO3zPUdQesYoQfwB?w=800&h=800',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1I8CWI-wHN_if9gC8fKVxATb1XXIvIlmX?w=800&h=800',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1fyKZy0iLhsjpAvBmCcudLnC5xelwj7dR?w=800&h=800'
  },
  {
    id: '2d2',
    title: 'Windows XP Portfolio Website',
    category: '2d',
    type: 'Interactive Web Design',
    year: '2024',
    description: 'Comprehensive interactive portfolio website recreating the authentic Windows XP experience with modern web technologies and responsive design principles.',
    detailDescription: 'This ambitious web design project faithfully recreates the nostalgic Windows XP interface as a fully functional portfolio platform. The project demonstrates advanced frontend development skills, UI/UX design principles, and creative problem-solving by transforming a classic desktop operating system into an engaging web experience. Every detail from the authentic XP scrollbars to the taskbar animations was meticulously crafted to provide users with genuine nostalgia while showcasing professional work.',
    technique: 'Frontend Web Development and Interactive Design',
    equipment: 'React.js, TypeScript, Tailwind CSS, Figma Make Platform',
    digitalTools: 'React.js, TypeScript, Tailwind CSS v4, Motion/React, Figma, VS Code, Chrome DevTools',
    physicalTools: 'Laptop and Reference Screenshots from Windows XP',
    originalSize: 'Responsive Web Application (1920px+ Desktop Optimized)',
    medium: 'Interactive Web Application, Progressive Web App',
    assignmentStatus: 'Personal Portfolio Project',
    designIntentions: 'I aimed to create a unique portfolio experience that combines nostalgic appeal with modern functionality, demonstrating both technical proficiency and creative vision while paying homage to the beloved Windows XP interface that defined an era of computing.',
    imageUrl1: 'https://lh3.googleusercontent.com/d/1dY1Fvtv6Bt9MXUMA4s45awSm8CaUAvTH',
    imageUrl2: 'https://lh3.googleusercontent.com/d/1wQm2nC_Mh2cSfIpIIcko7VSDHPLcQxo4',
    featuredImageUrl: 'https://lh3.googleusercontent.com/d/1klpa_0JdDjSxwG8bUuvUOM4fkszHKnWA'
  },
  {
    id: '2d3',
    title: 'Climate Data Infographic Magazine - Work in Progress',
    category: '2d',
    type: 'Editorial Design',
    year: '2024',
    description: 'Magazine layout design featuring complex climate data visualizations, balancing scientific accuracy with accessible visual communication.',
    detailDescription: 'This editorial project transforms dense scientific data into engaging visual narratives. The design challenge involved making complex information accessible while maintaining scientific integrity.',
    technique: 'Data Visualization and Editorial Layout',
    equipment: 'Adobe InDesign, Illustrator for Charts, Color-Calibrated Monitor',
    digitalTools: 'Adobe InDesign, Adobe Illustrator, Adobe Acrobat Pro, Tableau for Data Analysis',
    physicalTools: 'Color Calibration Hardware, Paper Sample Library, Loupe for Print Quality',
    originalSize: '8.5" x 11" (Standard Magazine Format)',
    medium: 'Print Layout Design, Data Visualization',
    assignmentStatus: 'Class Assignment - Information Design',
    designIntentions: 'I sought to make climate science more accessible to general audiences by using clear visual hierarchy and compelling data visualizations that tell a story while maintaining scientific accuracy.',
    imageUrl1: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=800',
    imageUrl2: 'https://images.unsplash.com/photo-1542744173-05336fcc7ad4?w=800&h=800',
    featuredImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800'
  },
  {
    id: '2d4',
    title: 'Transit App Redesign - Work in progress',
    category: '2d',
    type: 'UI/UX Design',
    year: '2024',
    description: 'Mobile application interface redesign focusing on accessibility and real-time transit information for urban commuters.',
    detailDescription: 'This UX project addressed usability issues in existing transit apps through user research, prototyping, and iterative design. Special attention was paid to accessibility and stress-case scenarios.',
    technique: 'User Interface Design and Prototyping',
    equipment: 'Figma for Design, Principle for Prototyping, User Testing',
    digitalTools: 'Figma, Adobe XD, Principle, Miro for User Journey Mapping, InVision for Prototypes',
    physicalTools: 'iPad Pro for Wireframing, Sticky Notes for Ideation, Whiteboard Sessions',
    originalSize: '9" x 16" (Mobile Screen Dimensions)',
    medium: 'Digital Interface Design, Interactive Prototype',
    assignmentStatus: 'Class Assignment - Interaction Design Studio',
    designIntentions: 'I focused on reducing cognitive load for stressed commuters by prioritizing essential information and creating clear visual hierarchy, while ensuring the interface remains accessible to users with diverse abilities.',
    imageUrl1: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=800',
    imageUrl2: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&h=800',
    featuredImageUrl: 'https://images.unsplash.com/photo-1559028006-448665bd7c7f?w=800&h=800'
  }
];